# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               Christopher Ahern
tagline:             'Data scientist at Oncora Medical'
description:         ''
url:                 http://christopherahern.github.io
baseurl:             ''
paginate:            3
gems:               [jekyll-paginate,jekyll-feed]
# About/contact
author:
  name:              Christopher Ahern
  url:               https://twitter.com/mdo
  email:             christopher.ahern@gmail.com
  github:            christopherahern
  linkedin:          christopherahern


# Custom vars
version:             1.0.0
